- name: authCloud
  hosts: localhost
  tasks:
    - name: info
      #to get uri /v3/auth/tokens
      uri: 
       url: https://iam.na-mexico-1.myhuaweicloud.com/v3/auth/tokens
       headers:
        Content-Type: "application/json;charset=utf8"
       body:
        auth: 
           identity: 
               methods: password
                   password: 
                       user: 
                           name: "hwstaff_intl_e00601829"
                           password: "Alemania2021#"
                           domain: 
                           name: "hwstaff_intl_e00601829"         
                    scope: 
                       domain: 
                           name: "hwstaff_intl_e00601829"  
      register: login
      
